### ISSUE TITLE
steal this travis setup

### ISSUE THREAD

**Issue by ORESoftware** [sumanjs/suman#242]
https://github.com/mochajs/mocha/blob/219edbabb590b71bb866e61c6d862b510dfdd6f3/.travis.yml

```yaml

sudo: false

# trust dist provides a modern build chain (as opposed to 'precise' dist)
# which absolves us from having to install compilers and stuff
dist: trusty

language: node_js

env:
  global:
    # phantomjs hosts binaries @ bitbucket, which has fairly restrictive
    # rate-limiting.  pull it from this sketchy site in China instead.
    - PHANTOMJS_CDNURL='https://cnpmjs.org/downloads'

matrix:
  fast_finish: true
  include:
    - node_js: '9'
      env: TARGET=test-node COVERAGE=true
    - node_js: '8'
      env: TARGET=test-node COVERAGE=true
    - node_js: '6'
      env: TARGET=test-node
    - node_js: '4'
      env: TARGET=test-node
    - node_js: '8'
      env: TARGET=lint
    - node_js: '8'
      env: TARGET=test-browser

before_install: scripts/travis-before-install.sh

before_script: scripts/travis-before-script.sh

script: make $TARGET

after_success: npm run coveralls

notifications:
  email: false
  urls:
    # for gitter mochajs/mocha
    - secure: fUrHenYJs+pTuLtgBRoYyrlyfVekxaIGmLWq7bhUUqBj/7p5eCkQFn13LlPht0/4WWZOiPBcdTN7tKnz3Ho7ATUJhAchvOWDUgL5gtTvOzeCHbPuCvHz/VLK6hMoPdbLA45M864NDLotfHvyh62WgQaVw9iPc80eb+umaDPrYiU=
    # for gitter mochajs/contributors
    - secure: rGMGYWBaZgEa9i997jJHKzjI8WxECqLi6BqsMhvstDq9EeTeXkZFVfz4r6G3Xugsk3tFwb/pDpiYo1OK36kA5arUJTCia51u4Wn+c7lHKcpef/vXztoyucvw6/jXdVm/FQz1jztYYbqdyAOWC2BV8gYvg5F8TpK05UGCe5R0bRA=
  on_success: change
  on_failure: always

addons:
  artifacts:
    paths:
      - .karma/
      - ./mocha.js
  sauce_connect: true
cache:
  directories:
    - ~/.npm
```
